param(
    [string]$Dir = "replays",
    # Per-FLOOR turn caps, not per-run: a run that descends keeps playing until it dies or runs out of
    # floors, so a cap of 40 still yielded 5878 steps. These are sized for a corpus that stays small
    # enough to check in and quick enough to rebuild.
    [int]$LongTurns = 120,
    [int]$ShortTurns = 15,
    [int]$DeathTurns = 60,
    # Per-recording ceiling. A run that stops progressing still owns its process, so it is killed rather
    # than left to block the corpus build.
    [int]$PerFileSeconds = 300
)

# Rebuilds the committed replay corpus from the current engine, then proves each file reproduces.
#
# Why a script rather than a note: a corpus regenerated by hand goes stale silently and then fails for
# the wrong reason. Every file here is produced by a command that is written down, so the next engine
# change regenerates it the same way - and the proof step means a fixture that does not reproduce is
# reported here rather than discovered later by someone using it.
#
# The old corpus predated the RNG repair, so those recordings reproduced nothing: they were readable
# but dead, which is the worst state for a fixture to be in.

$ErrorActionPreference = 'Stop'

# Fresh jars and a freshly written classpath, deliberately. A stale superintelligence jar means these
# files are produced by a build that is not the one being tested, and the symptom is a header the reader
# refuses. replaycp is asked for rather than assumed, because after a clean it does not exist and
# reading it anyway is a confusing failure rather than an obvious one.
Write-Host "building jars and classpath..."
& ./gradlew :superintelligence:jar :core:jar :desktop:replaycp -q
if ($LASTEXITCODE -ne 0) { throw "build failed" }

$cp = (Get-Content 'desktop\build\replay-classpath.txt' -Raw).Trim()
$cp = "$cp;superintelligence\build\classes\java\main;superintelligence\build\resources\main"
$main = 'com.shatteredpixel.shatteredpixeldungeon.superintelligence.Main'

if (-not (Test-Path $Dir)) { New-Item -ItemType Directory -Path $Dir | Out-Null }

function Get-Termination {
    param($Output)
    $joined = ($Output -join "`n")
    foreach ($reason in @('DEATH', 'VICTORY', 'TURN_LIMIT', 'STALLED')) {
        if ($joined -match "outcome\s+$reason") { return $reason }
    }
    return "?"
}

function Invoke-Rollout {
    param([string]$Name, [string]$Hero, [int]$Turns)

    $path = Join-Path $Dir "$Name.replay"
    $job = Start-Job -ScriptBlock {
        param($cp, $main, $seed, $hero, $turns, $path)
        & java -cp $cp $main rollout --seed $seed --hero $hero --max-turns $turns --save $path --no-color 2>&1
    } -ArgumentList $cp, $main, $Name, $Hero, $Turns, $path

    if (Wait-Job $job -Timeout $PerFileSeconds) {
        $out = Receive-Job $job
        if (Test-Path $path) {
            $steps = (Get-Content $path | Select-String -Pattern '^[A-Z_]+ ' ).Count
            Write-Host ("  {0,-22} {1,-10} {2,6} steps  {3}" -f $Name, $Hero, $steps, (Get-Termination $out))
        } else {
            Write-Host "  $Name produced no file"
        }
    } else {
        Stop-Job $job
        Write-Host "  $Name TIMED OUT after ${PerFileSeconds}s"
    }
    Remove-Job $job -Force
}

Write-Host "recording corpus into $Dir"
# HeroClass is WARRIOR MAGE ROGUE HUNTRESS DUELIST CLERIC - there is no THIEF or RANGER, and passing one
# is an IllegalArgumentException that costs a whole recording slot to discover.
foreach ($hero in @('WARRIOR', 'MAGE', 'ROGUE', 'HUNTRESS', 'DUELIST', 'CLERIC')) {
    Invoke-Rollout -Name "$($hero.ToLower())-short" -Hero $hero -Turns $ShortTurns
}
foreach ($hero in @('WARRIOR', 'MAGE')) {
    Invoke-Rollout -Name "$($hero.ToLower())-long" -Hero $hero -Turns $LongTurns
}

# A run that ended in death rather than a limit, so the corpus covers the case where the hero is gone
# rather than merely stopped. Scanned rather than assumed: which seed dies is a property of the world,
# not something a fixed list can promise.
Write-Host "searching for a death-terminated run"
for ($i = 0; $i -lt 12; $i++) {
    $seed = "death-probe-$i"
    $path = Join-Path $Dir "warrior-death.replay"
    $job = Start-Job -ScriptBlock {
        param($cp, $main, $seed, $hero, $path)
        & java -cp $cp $main rollout --seed $seed --hero $hero --max-turns $DeathTurns --save $path --no-color 2>&1
    } -ArgumentList $cp, $main, $seed, 'WARRIOR', $path
    if (Wait-Job $job -Timeout $PerFileSeconds) {
        $out = Receive-Job $job
        if (($out -join "`n") -match 'outcome\s+DEATH') {
            Write-Host "  warrior-death          WARRIOR    $seed"
            break
        }
    } else { Stop-Job $job }
    Remove-Job $job -Force
    if (Test-Path $path) { Remove-Item $path }
}

Write-Host "verifying every recording reproduces"
# A recording that does not reproduce is not committed. Leaving it in place would mean the corpus fails
# for a reason unrelated to whatever the next reader is investigating, and the old corpus was exactly
# that: readable, listed by the catalog, and reproducing nothing. Rejected files are kept under
# rejected/ so the failure is inspectable rather than silent.
$rejected = Join-Path $Dir 'rejected'
$bad = @()
foreach ($f in Get-ChildItem $Dir -File -Filter *.replay | Sort-Object Name) {
    $out = & java -cp $cp $main verify $f.FullName --no-color 2>&1
    if ($out -match '\[OK\]') {
        $steps = (Select-String -InputObject ($out -join "`n") -Pattern 'steps=(\d+)').Matches.Groups[1].Value
        Write-Host ("  {0,-24} reproduces ({1} steps)" -f $f.Name, $steps)
    } else {
        if (-not (Test-Path $rejected)) { New-Item -ItemType Directory -Path $rejected | Out-Null }
        Move-Item $f.FullName (Join-Path $rejected $f.Name) -Force
        $bad += $f.Name
        Write-Host ("  {0,-24} DOES NOT REPRODUCE - moved to rejected/" -f $f.Name) -ForegroundColor Red
        ($out -join "`n") -split "`n" | Select-String -Pattern '\[ERROR\]|replayed|recorded' |
            Select-Object -First 3 | ForEach-Object { Write-Host "      $($_.Line.Trim())" }
    }
}

$kept = (Get-ChildItem $Dir -File -Filter *.replay).Count
Write-Host "corpus rebuilt: $kept recordings, all reproduce"
if ($bad.Count -gt 0) {
    Write-Host "$($bad.Count) recording(s) rejected: $($bad -join ', ')" -ForegroundColor Yellow
    exit 1
}